name: 🌟 Propose New Semantic Anchor
description: Suggest a new semantic anchor for the catalog
title: "[New Anchor]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a new semantic anchor! Please fill out the form below.

        **Before submitting**, test your anchor with an LLM:
        ```
        What concepts do you associate with '<your anchor name>'?
        ```

        A good semantic anchor should trigger specific, rich, and consistent conceptual activation.

  - type: input
    id: anchor-name
    attributes:
      label: Anchor Name
      description: The name/term of the semantic anchor
      placeholder: e.g., "SOTA" (State of the Art)
    validations:
      required: true

  - type: textarea
    id: why-semantic-anchor
    attributes:
      label: Why is this a semantic anchor?
      description: |
        Explain why this qualifies as a semantic anchor:
        - **Precise**: References specific, established knowledge
        - **Rich**: Activates multiple interconnected concepts
        - **Consistent**: Different users get similar activation
        - **Attributable**: Can be traced to key proponents/standards
      placeholder: |
        This term triggers...
        It's established in...
        Key concepts include...
    validations:
      required: true

  - type: input
    id: full-name
    attributes:
      label: Full Name (if different)
      placeholder: e.g., "State of the Art"

  - type: input
    id: aka
    attributes:
      label: Also Known As
      description: Alternative names or abbreviations
      placeholder: e.g., "cutting-edge, leading-edge"

  - type: textarea
    id: core-concepts
    attributes:
      label: Core Concepts
      description: Key concepts that this anchor activates
      placeholder: |
        - Concept 1
        - Concept 2
        - Concept 3

  - type: input
    id: proponents
    attributes:
      label: Key Proponents
      description: Authors, standards bodies, or originators
      placeholder: e.g., "Martin Fowler, Kent Beck"

  - type: dropdown
    id: categories
    attributes:
      label: Category
      description: Which category does this anchor belong to?
      options:
        - Testing & Quality Practices
        - Architecture & Design
        - Design Principles & Patterns
        - Requirements Engineering
        - Documentation
        - Communication & Presentation
        - Decision Making & Strategy
        - Development Practices
        - Statistical Methods & Process Monitoring
        - Interaction & Reasoning Patterns
        - Not sure / Other
    validations:
      required: true

  - type: textarea
    id: roles
    attributes:
      label: Relevant Professional Roles
      description: Which roles would benefit from this anchor?
      placeholder: |
        - Software Developer
        - Software Architect
        - QA Engineer
        etc.

  - type: textarea
    id: use-cases
    attributes:
      label: When to Use
      description: When should someone invoke this anchor?
      placeholder: |
        - When discussing...
        - In the context of...
        - To clarify...

  - type: textarea
    id: related-anchors
    attributes:
      label: Related Anchors
      description: Existing semantic anchors that are related
      placeholder: e.g., "TDD, London School", "Clean Architecture"

  - type: textarea
    id: llm-test-result
    attributes:
      label: LLM Test Result
      description: Paste the result from testing this anchor with an LLM
      placeholder: |
        Prompt: "What concepts do you associate with 'SOTA'?"
        Response: [paste LLM response]

  - type: checkboxes
    id: quality-checklist
    attributes:
      label: Quality Checklist
      description: Verify your anchor meets these criteria
      options:
        - label: Precise (references specific knowledge with clear boundaries)
          required: true
        - label: Rich (activates multiple interconnected concepts)
          required: true
        - label: Consistent (different users get similar activation)
          required: true
        - label: Attributable (traceable to proponents/publications/standards)
          required: true
        - label: I have tested this with an LLM and it shows good recognition
          required: true
